FROM scratch AS closure
# We'll add the closure files here
COPY /nix/store/8pfvdrk63blqg22nkqs64ywzl5v64bby-clementine-cli-arm-linux-gnueabihf-0.1.0 /nix/store/8pfvdrk63blqg22nkqs64ywzl5v64bby-clementine-cli-arm-linux-gnueabihf-0.1.0
# Copy all dependencies too - you'll need to copy the entire closure

FROM arm32v7/debian:sid

COPY --from=closure /nix/store /nix/store

ENTRYPOINT ["/nix/store/8pfvdrk63blqg22nkqs64ywzl5v64bby-clementine-cli-arm-linux-gnueabihf-0.1.0"]
